# Generated by Django 4.0.1 on 2022-01-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genre_profile_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='genre',
            new_name='user_type',
        ),
    ]
