# Generated by Django 4.0.1 on 2022-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_genre_type_rename_genre_profile_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_time',
        ),
    ]
