# Generated by Django 4.0.1 on 2022-01-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
