# Generated by Django 4.0.1 on 2022-01-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureFormat',
            new_name='Format',
        ),
    ]
