# Generated by Django 4.0.1 on 2022-01-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_lectureformat_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
    ]
