# Generated by Django 4.0.1 on 2022-01-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_id_collection_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='format_id',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='user_id',
            new_name='user',
        ),
    ]
