# Generated by Django 4.0.1 on 2022-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_genre_id_entity_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=12),
            preserve_default=False,
        ),
    ]
