# Generated by Django 4.0.1 on 2022-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_entity_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
