# Generated by Django 4.0.1 on 2022-02-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_entity_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='serial_number2',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
