# Generated by Django 4.0.1 on 2022-02-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_entity_serial_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='serial_number',
            field=models.IntegerField(default=2134),
            preserve_default=False,
        ),
    ]
