# Generated by Django 4.0.1 on 2022-02-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_recipient_id_notification_recipient_and_more'),
        ('course', '0011_entity_serial_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Wishlist',
        ),
    ]
