# Generated by Django 4.0.1 on 2022-02-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_collection_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
