# Generated by Django 4.0.1 on 2022-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_entity_slug_remove_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_visible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
