# Generated by Django 4.0.1 on 2022-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_entity_is_visible_alter_entity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='media',
            field=models.ImageField(blank=True, default='profiles/about-us-video.mp4', null=True, upload_to='profiles/'),
        ),
    ]
