# Generated by Django 4.0.1 on 2022-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
