# Generated by Django 4.0.1 on 2022-03-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
    ]
