# Generated by Django 4.0.1 on 2022-03-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
