# Generated by Django 4.0.1 on 2022-01-27 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('intro', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('score', models.IntegerField(default=1)),
                ('is_finish', models.BooleanField(default=False, null=True)),
                ('is_excellent', models.BooleanField(default=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('homework_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.assignment')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
