# Generated by Django 4.0.1 on 2022-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_execution_is_excellent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
