# Generated by Django 4.0.1 on 2022-02-16 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_assignment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='is_finish',
        ),
        migrations.AddField(
            model_name='execution',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
