# Generated by Django 4.0.1 on 2022-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_remove_execution_is_finish_execution_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
