# Generated by Django 4.0.1 on 2022-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_execution_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='content_media',
            field=models.ImageField(blank=True, default='profiles/about-us-video.mp4', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='execution',
            name='content_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
