# Generated by Django 4.0.1 on 2022-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_remove_executionmedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionmedia',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
