# Generated by Django 4.0.1 on 2022-03-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_executionmedia_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionMedia',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
