# Generated by Django 4.0.1 on 2022-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_delete_executionmedia_delete_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='content_media',
            field=models.ImageField(blank=True, default='profiles/about-us-video.mp4', null=True, upload_to='profiles/'),
        ),
    ]
