# Generated by Django 4.0.1 on 2022-03-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_mediatype_remove_execution_content_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='content_text',
        ),
    ]
