# Generated by Django 4.0.1 on 2022-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_remove_execution_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='content_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
