# Generated by Django 4.0.1 on 2022-03-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0019_rename_executionmedia_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='score',
        ),
    ]
