# Generated by Django 4.0.1 on 2022-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0020_remove_execution_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
