# Generated by Django 4.0.1 on 2022-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0022_executionstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='finish_time',
        ),
    ]
