# Generated by Django 4.0.1 on 2022-03-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0023_remove_execution_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
